---
name: Validate PR
on:
  pull_request:
    branches: [master]
jobs:
  lint:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1'
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: |
          go vet -v ./...
      - name: Test
        run: |
          go test -v ./...
